ListenAddr = ":8080"
DockerURL = "tcp://ucp.engineering-cdl.es.paascloud.oneadp.com:443"
TLSCACert = "C:\\Rajan\\admin-bundle\\ca.pem"
TLSCert = "C:\\Rajan\\admin-bundle\\cert.pem"
TLSKey = "C:\\Rajan\\admin-bundle\\key.pem"
ActiveActiveSrvcsCnslPath = "maersk/docker-gateway/ucp.engineering-cdl.es.paascloud.oneadp.com/active-active-services" 
BuddyCluster = "ucp.nas-cdl.es.ad.adp.com"
RemoteGateWayCnslPath = "maersk/docker-gateway/ucp.nas-cdl.es.ad.adp.com/gatewayrouter/nginxplus"
AllowInsecure = false
PollInterval = "15s"
ConsulHost = "cdlcldvmg0013.es.ad.adp.com"
ConsulPort = 8500
ConsulTemplate = "C:\\Rajan\\consul-template"
DefaultHealthChkURI = "/health"
DefaultHealthChkInterval = "10"
DefaultHealthChkFails = "1"
DefaultHealthChkPasses = "1"	   
	   
[NginxPlusConfig]
Name = "nginxplus"
ConfigPath = "/etc/nginx/nginx.conf"
PidPath = "/etc/nginx/nginx.pid"
TemplatePath = "C:\\Rajan\\nginx.conf.template"
BackendOverrideAddress = ""
ConnectTimeout = 5000
ServerTimeout = 10000
ClientTimeout = 10000
MaxConn = 1024
Port = 80
SyslogAddr = ""
AdminUser = "admin"
AdminPass = ""
SSLCertPath = ""
SSLCert = ""
SSLPort = 0
SSLOpts = ""
User = "www-data"
WorkerProcesses = 2
RLimitNoFile = 65535
ProxyConnectTimeout = 600
ProxySendTimeout = 600
ProxyReadTimeout = 600
SendTimeout = 600
SSLCiphers = "HIGH:!aNULL:!MD5"
SSLProtocols = "SSLv3 TLSv1 TLSv1.1 TLSv1.2"
NginxPlusEnabled = false