version : "2"
services:
   vote_S1DC2:
            image: dtr.cdl.es.ad.adp.com/paas/instavote:1.0
            ports:
                 - 80
            labels:
                  - "interlock.hostname=vote.s1.dc2"
                  - "interlock.domain=paascloud.oneadp.com"
                  - "interlock.alias_domain.0=vote.s1.dc1.paascloud.oneadp.com"
                  - "dockergateway.activeactive=true"
                  - "dockergateway.health_check_uri=/"
                  - "dockergateway.health_check_interval=5"
                  - "dockergateway.health_check_fails=1"
                  - "dockergateway.health_check_passes=1"
            restart: always
            
   vote_S2DC2:
            image: dtr.cdl.es.ad.adp.com/paas/instavote:1.0
            ports:
                 - 80
            labels:
                  - "interlock.hostname=vote.s2.dc2"
                  - "interlock.domain=paascloud.oneadp.com"
                  - "interlock.alias_domain.0=vote.s2.dc1.paascloud.oneadp.com"
                  - "dockergateway.activeactive=true"
                  - "dockergateway.health_check_uri=/"
                  - "dockergateway.health_check_interval=5"
                  - "dockergateway.health_check_fails=1"
                  - "dockergateway.health_check_passes=1"
            restart: always
