version : "2"
services:
   vote_S1DC2:
            image: cozysystems.net/cloud/instavote:1.0
            ports:
                 - 80
            labels:
                  - "interlock.hostname=vote.s1.dc2"
                  - "interlock.domain=cloudcloud.cozysystems.net"
                  - "interlock.alias_domain.0=vote.s1.dc1.cloudcloud.cozysystems.net"
                  - "dockergateway.activeactive=true"
                  - "dockergateway.health_check_uri=/"
                  - "dockergateway.health_check_interval=5"
                  - "dockergateway.health_check_fails=1"
                  - "dockergateway.health_check_passes=1"
            restart: always
            
   vote_S2DC2:
            image: cozysystems.net/cloud/instavote:1.0
            ports:
                 - 80
            labels:
                  - "interlock.hostname=vote.s2.dc2"
                  - "interlock.domain=cloudcloud.cozysystems.net"
                  - "interlock.alias_domain.0=vote.s2.dc1.cloudcloud.cozysystems.net"
                  - "dockergateway.activeactive=true"
                  - "dockergateway.health_check_uri=/"
                  - "dockergateway.health_check_interval=5"
                  - "dockergateway.health_check_fails=1"
                  - "dockergateway.health_check_passes=1"
            restart: always
